export const topTabArray = [
  {id: 1, title: 'Sailing', isSelected: true},
  {id: 2, title: 'Port', isSelected: false},
  {id: 3, title: 'Dock', isSelected: false},
];

export const sailingData = [
  {
    id: 1,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'PACKAGED AIR CON. FOR ENG. CONT. ROOM',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 2,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 3,
    tag: 'PCM',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 4,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 5,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 6,
    tag: 'PCM',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 7,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 8,
    tag: 'PCM',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 9,
    tag: 'PCM',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 10,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
];

export const checkInNewSpareList = [
  {
    id: 1,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 2,
    tag: 'Not Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 3,
    tag: 'Partial',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 4,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 5,
    tag: 'Not Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 6,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 7,
    tag: 'Partial',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 8,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 9,
    tag: 'Partial',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 10,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
];

export const checkInDockList = [
  {
    id: 1,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 2,
    tag: 'Not Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 3,
    tag: 'Partial',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 4,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 5,
    tag: 'Not Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 6,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 7,
    tag: 'Partial',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 8,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 9,
    tag: 'Partial',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 10,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
];

export const detailData = [
  {
    id: 1,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
  {
    id: 2,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
  {
    id: 3,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
  {
    id: 4,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
  {
    id: 5,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
];

export const checkInSpareList = [
  {
    id: 1,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 2,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 3,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 4,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 5,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 6,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 7,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 8,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
];

export const checkInDetailList = [
  {
    id: 1,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 2,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 3,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'by Hyundai',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 4,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'by Hyundai',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 5,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 6,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 7,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 8,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
];

export const inventoryDetailList = [
  {
    id: 1,
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
  {
    id: 2,
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
  {
    id: 3,
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'by Hyundai',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
  {
    id: 4,
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'by Hyundai',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
  {
    id: 5,
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
  {
    id: 6,
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
  {
    id: 7,
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
  {
    id: 8,
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
];

export const inventoryScanList = [
  {
    id: 1,
    tag: 'Available',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
  {
    id: 2,
    tag: 'Available',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
  {
    id: 3,
    tag: 'Missing',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'by Hyundai',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
  {
    id: 4,
    tag: 'Missing',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'by Hyundai',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
  {
    id: 5,
    tag: 'Available',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
  {
    id: 6,
    tag: 'Missing',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
  {
    id: 7,
    tag: 'Available',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
  {
    id: 8,
    tag: 'Available',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
  },
];

export const inventoryAddList = [
  {
    id: 1,
    tag: 'Reconditioned',
    title: 'Spare Part Name will be here',
    uniqueID: '4765-1901-0004',
    qty: '05',
  },
  {
    id: 2,
    tag: 'New',
    title: 'Spare Part Name will be here',
    uniqueID: '4765-1901-0004',
    qty: '12',
  },
  {
    id: 3,
    tag: 'Reconditioned',
    title: 'Spare Part Name will be here',
    uniqueID: '4765-1901-0004',
    qty: '03',
  },
  {
    id: 4,
    tag: 'New',
    title: 'Spare Part Name will be here',
    uniqueID: '4765-1901-0004',
    qty: '19',
  },
  {
    id: 5,
    tag: 'New',
    title: 'Spare Part Name will be here',
    uniqueID: '4765-1901-0004',
    qty: '08',
  },
  {
    id: 6,
    tag: 'Reconditioned',
    title: 'Spare Part Name will be here',
    uniqueID: '4765-1901-0004',
    qty: 23,
  },
  {
    id: 7,
    tag: 'New',
    title: 'Spare Part Name will be here',
    uniqueID: '4765-1901-0004',
    qty: '23',
  },
  {
    id: 8,
    tag: 'Reconditioned',
    title: 'Spare Part Name will be here',
    uniqueID: '4765-1901-0004',
    qty: '17',
  },
];

export const checkOutList = [
  {
    id: 1,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 2,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 3,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 4,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 5,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 6,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 7,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 8,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
];

export const inventorySecondFloorList = [
  {
    id: 1,
    title: 'Main Engine (Hyundai Heavy Industry)',
  },
  {
    id: 2,
    title: 'Generator Engine (STX)',
  },
  {
    id: 3,
    title: 'Generator Engine (STX)',
  },
  {
    id: 4,
    title: 'Generator Engine (STX)',
  },
  {
    id: 5,
    title: 'Main Engine (Hyundai Heavy Industry) ',
  },
  {
    id: 6,
    title: 'Main Air Compressor (Samgong)',
  },
  {
    id: 7,
    title: 'Main Air Compressor (Samgong)',
  },
  {
    id: 8,
    title: 'Generator Engine (STX)',
  },
  {
    id: 9,
    title: 'Main Air Compressor (Samgong)',
  },
  {
    id: 10,
    title: 'Main Engine (Hyundai Heavy Industry)',
  },
  {
    id: 11,
    title: 'Main Engine (Hyundai Heavy Industry)',
  },
  {
    id: 12,
    title: 'Main Engine (Hyundai Heavy Industry) ',
  },
];

export const periodMenu = [
  {
    id: 1,
    title: 'Daily',
    value: 'daily',
  },
  {
    id: 2,
    title: 'Weekly',
    value: 'weekly',
  },
  {
    id: 3,
    title: 'Monthly',
    value: 'monthly',
  },
];

export const statusMenu = [
  {
    id: 1,
    title: 'Planning',
    value: 'planning',
    color: '#0FABA6',
  },
  {
    id: 2,
    title: 'In-Progress',
    value: 'in_progress',
    color: '#107FCA',
  },
  {
    id: 3,
    title: 'Complete',
    value: 'completed',
    color: '#3ABB5D',
  },
];

export const inventoryTypeButtons = [
  {
    id: 1,
    title: 'Metal Parts',
    isSelected: false,
  },
  {
    id: 2,
    title: 'Shelves',
    isSelected: false,
  },
  {
    id: 3,
    title: 'Both',
    isSelected: false,
  },
];

export const roomNamesButtons = [
  {
    id: 1,
    title: 'Generator inventory Rack',
    isSelected: false,
  },
  {
    id: 2,
    title: 'Lorem ipsum room',
    isSelected: false,
  },
  {
    id: 3,
    title: 'One more room',
    isSelected: false,
  },
];

export const sparePartsList = [
  {
    id: 1,
    name: 'Material Description',
    uniqueID: '4765-1901-0004',
    isSelected: false,
  },
  {
    id: 2,
    name: 'Material Description',
    uniqueID: '4765-1901-0004',
    isSelected: false,
  },
  {
    id: 3,
    name: 'Material Description',
    uniqueID: '4765-1901-0004',
    isSelected: false,
  },
  {
    id: 4,
    name: 'Material Description',
    uniqueID: '4765-1901-0004',
    isSelected: false,
  },
  {
    id: 5,
    name: 'Material Description',
    uniqueID: '4765-1901-0004',
    isSelected: false,
  },
  {
    id: 6,
    name: 'Material Description',
    uniqueID: '4765-1901-0004',
    isSelected: false,
  },
  {
    id: 7,
    name: 'Material Description',
    uniqueID: '4765-1901-0004',
    isSelected: false,
  },
  {
    id: 8,
    name: 'Material Description',
    uniqueID: '4765-1901-0004',
    isSelected: false,
  },
];
