export const topTabArray = [
  {id: 1, title: 'Sailing', isSelected: true},
  {id: 2, title: 'Port', isSelected: false},
  {id: 3, title: 'Dock', isSelected: false},
];

export const sailingData = [
  {
    id: 1,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'PACKAGED AIR CON. FOR ENG. CONT. ROOM',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 2,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 3,
    tag: 'PCM',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 4,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 5,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 6,
    tag: 'PCM',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 7,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 8,
    tag: 'PCM',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 9,
    tag: 'PCM',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 10,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
];

export const detailData = [
  {
    id: 1,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
  {
    id: 2,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
  {
    id: 3,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
  {
    id: 4,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
  {
    id: 5,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
];
