export const topTabArray = [
  {id: 1, title: 'Sailing', isSelected: true},
  {id: 2, title: 'Port', isSelected: false},
  {id: 3, title: 'Dock', isSelected: false},
];

export const sailingData = [
  {
    id: 1,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'PACKAGED AIR CON. FOR ENG. CONT. ROOM',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 2,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 3,
    tag: 'PCM',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 4,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 5,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 6,
    tag: 'PCM',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 7,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 8,
    tag: 'PCM',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 9,
    tag: 'PCM',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
  {
    id: 10,
    tag: 'PMS',
    date: '18/02/2024',
    title: 'H.F.O. Purifier',
    desc: 'Inspect & Retighten - Counterweight, main & guide Bearing CAP',
  },
];

export const checkInNewSpareList = [
  {
    id: 1,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 2,
    tag: 'Not Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 3,
    tag: 'Partial',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 4,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 5,
    tag: 'Not Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 6,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 7,
    tag: 'Partial',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 8,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 9,
    tag: 'Partial',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 10,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
];

export const checkInDockList = [
  {
    id: 1,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 2,
    tag: 'Not Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 3,
    tag: 'Partial',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 4,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 5,
    tag: 'Not Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 6,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 7,
    tag: 'Partial',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 8,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 9,
    tag: 'Partial',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
  {
    id: 10,
    tag: 'Received',
    PoNo: '10212008080921',
    desc: 'SUNGDONG SHIPBUILDING & MARINE ENGINEERING',
  },
];

export const detailData = [
  {
    id: 1,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
  {
    id: 2,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
  {
    id: 3,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
  {
    id: 4,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
  {
    id: 5,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    uniqueID: '4765-1901-0004',
    rob: 23,
    workingReplace: 23,
    pkgQty: 23,
    checkoutQty: 23,
  },
];

export const checkInSpareList = [
  {
    id: 1,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 2,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 3,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 4,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 5,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 6,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 7,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 8,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    scannedQty: 23,
    checkinQty: 23,
  },
];
export const checkOutList = [
  {
    id: 1,
    tag: 'Reconditioned',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 2,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 3,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 4,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 5,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 6,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 7,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
  {
    id: 8,
    tag: 'New',
    title: 'CCU MULTI PURPOSE CONTROLLER, MPC-10',
    desc: 'Machinery • Manufacturer',
    uniqueID: '4765-1901-0004',
    rob: 23,
    scannedQty: 23,
    checkinQty: 23,
  },
];

export const inventorySecondFloorList = [
  {
    id: 1,
    title: 'Main Engine (Hyundai Heavy Industry)',
  },
  {
    id: 2,
    title: 'Generator Engine (STX)',
  },
  {
    id: 3,
    title: 'Generator Engine (STX)',
  },
  {
    id: 4,
    title: 'Generator Engine (STX)',
  },
  {
    id: 5,
    title: 'Main Engine (Hyundai Heavy Industry) ',
  },
  {
    id: 6,
    title: 'Main Air Compressor (Samgong)',
  },
  {
    id: 7,
    title: 'Main Air Compressor (Samgong)',
  },
  {
    id: 8,
    title: 'Generator Engine (STX)',
  },
  {
    id: 9,
    title: 'Main Air Compressor (Samgong)',
  },
  {
    id: 10,
    title: 'Main Engine (Hyundai Heavy Industry)',
  },
  {
    id: 11,
    title: 'Main Engine (Hyundai Heavy Industry)',
  },
  {
    id: 12,
    title: 'Main Engine (Hyundai Heavy Industry) ',
  },
];
